### ISSUE TITLE
金榜创造营 定时任务时间目测不对。

### ISSUE THREAD

**Issue by dpigu** [qqsdff/script#2]
#金榜创造营
0 8 21-31 5-12 * 
大佬时间是不是弄错了，5-12月的21-31日运行？

**Comment by andy31009** [comment]
> #金榜创造营
> 0 8 21-31 5-12 *
> 大佬时间是不是弄错了，5-12月的21-31日运行？

我也正想提出这个问题，想不到有人先行一步了

**Comment by qqsdff** [comment]
写错了
